package actions

import (
	"fmt"
	"log"
	"os"
	"os/exec"
)

type PythonEnvAction struct {
}

func (act PythonEnvAction) DoAction() error {
	act.makeMainFile()
	if err := act.permit(); err != nil {
		fmt.Errorf("could not permit run script: \n%s", err)
	}
	return nil
}

func (act PythonEnvAction) GetHelp() string {
	return "builds a python environment in the current directory"
}

func (act *PythonEnvAction) permit() error {
	// Run file permissions
	cmd := exec.Command("chmod", "+x", "./main.py")
	if err := cmd.Run(); err != nil {
		return err
	}
	return nil
}

func (act *PythonEnvAction) makeMainFile() {
	file := "main.py"
	if FileExists(file) {
		fmt.Printf("%s found, skipping generation", file)
		return
	}
	f, err := os.Create("./" + file)
	defer f.Close()
	if err != nil {
		log.Fatalf("Error creating main.go file: %s", err)
	}
	f.WriteString("#!/usr/bin/env python3\nprint(\"generated by jenv\")")
}
